### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by cybersea**
Change from pygments to rouge

### CODE REVIEW

**Comment by mapsam** [comment]
Heyo! What's the reason for the change @cybersea??

**Comment by aaronr** [comment]
@mapsam ... github does not support pygments and emits a warning every commit.  Documented here: https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors

**Comment by aaronr** [comment]
I tested this locally and everything seems to render just fine.  Merging.

**Comment by mapsam** [comment]
Great catch!

**Pull request merged**
