### PR TITLE
Proposing a quick talk

### PR DESCRIPTION
**Pull request by ARSimmons**
Adding myself to the agenda

### CODE REVIEW

**Comment by powersa** [comment]
@ARSimmons, well I'm very intrigued. Can you provide a little more info (just so people know what to expect)?

**Comment by powersa** [comment]
I love the title!

**Comment by ARSimmons** [comment]
Sure @powersa ...

I propose to talk (briefly) about some performance gains and optimizations that I discovered by using JSONB with PostgreSQL. I will show some (boring) legacy SQL functions that I cast into the JSONB format and created laser fast returns. Think geriatric Terminator getting a facelift and starring in (yet another) sequel. JSONB + your bad, slow code = "I WILL BE BACK".

**Comment by powersa** [comment]
Awesome, I added your description to the entry. Feel free to merge if it looks good to you! Excited to hear more about this. Thanks for adding yourself so early :)

**Pull request merged**
